// Mock data for demo — seeded with one high-risk property for impact
export const MOCK_PROPERTIES = [
  {
    id: '1',
    plotId: 'MH-PUN-2024-00147',
    owner: 'Rajesh Kumar Sharma',
    location: 'Kothrud, Pune, Maharashtra',
    price: 8500000,
    area: '1200 sq ft',
    type: 'Residential',
    status: 'safe',
    registrationDate: '2022-03-15',
    lastTransfer: '2022-03-15',
    ownershipChain: [
      { id: 'oc1', owner: 'Municipal Corp Pune', role: 'Original Allotment', timestamp: '1998-06-20', transferPrice: 450000, validationStatus: 'verified' },
      { id: 'oc2', owner: 'Vikas Patil', role: 'First Purchase', timestamp: '2005-11-10', transferPrice: 1200000, validationStatus: 'verified' },
      { id: 'oc3', owner: 'Sunita Deshmukh', role: 'Inheritance Transfer', timestamp: '2015-08-22', transferPrice: 3500000, validationStatus: 'verified' },
      { id: 'oc4', owner: 'Rajesh Kumar Sharma', role: 'Market Purchase', timestamp: '2022-03-15', transferPrice: 8500000, validationStatus: 'verified' },
    ],
  },
  {
    id: '2',
    plotId: 'MH-MUM-2024-00891',
    owner: 'Priya Mehta',
    location: 'Andheri West, Mumbai, Maharashtra',
    price: 25000000,
    area: '850 sq ft',
    type: 'Commercial',
    status: 'risky',
    registrationDate: '2024-01-08',
    lastTransfer: '2024-01-08',
    ownershipChain: [
      { id: 'oc5', owner: 'Land Development Authority', role: 'Original Grant', timestamp: '2010-02-14', transferPrice: 5000000, validationStatus: 'verified' },
      { id: 'oc6', owner: 'Amit Shah Enterprises', role: 'Commercial Purchase', timestamp: '2018-07-30', transferPrice: 12000000, validationStatus: 'verified' },
      { id: 'oc7', owner: 'Global Realty LLC', role: 'Quick Flip', timestamp: '2023-12-25', transferPrice: 18000000, validationStatus: 'suspicious' },
      { id: 'oc8', owner: 'Priya Mehta', role: 'Rapid Acquisition', timestamp: '2024-01-08', transferPrice: 25000000, validationStatus: 'suspicious' },
    ],
  },
  {
    id: '3',
    plotId: 'KA-BLR-2023-05521',
    owner: 'Deepak Narayan',
    location: 'Whitefield, Bangalore, Karnataka',
    price: 15000000,
    area: '2400 sq ft',
    type: 'Residential',
    status: 'safe',
    registrationDate: '2023-06-10',
    lastTransfer: '2023-06-10',
    ownershipChain: [
      { id: 'oc9', owner: 'BDA Bangalore', role: 'Allotment', timestamp: '2001-04-15', transferPrice: 800000, validationStatus: 'verified' },
      { id: 'oc10', owner: 'Srinivas Rao', role: 'Family Transfer', timestamp: '2010-09-20', transferPrice: 4000000, validationStatus: 'verified' },
      { id: 'oc11', owner: 'Deepak Narayan', role: 'Market Purchase', timestamp: '2023-06-10', transferPrice: 15000000, validationStatus: 'verified' },
    ],
  },
  {
    id: '4',
    plotId: 'DL-NDL-2024-02233',
    owner: 'Fatima Begum',
    location: 'Dwarka Sector 12, New Delhi',
    price: 18500000,
    area: '1800 sq ft',
    type: 'Residential',
    status: 'review',
    registrationDate: '2024-02-20',
    lastTransfer: '2024-02-20',
    ownershipChain: [
      { id: 'oc12', owner: 'DDA Delhi', role: 'Allotment', timestamp: '2005-01-10', transferPrice: 2000000, validationStatus: 'verified' },
      { id: 'oc13', owner: 'Ramesh Gupta', role: 'Purchase', timestamp: '2012-06-15', transferPrice: 7500000, validationStatus: 'verified' },
      { id: 'oc14', owner: 'Fatima Begum', role: 'Recent Transfer', timestamp: '2024-02-20', transferPrice: 18500000, validationStatus: 'verified' },
    ],
  },
  {
    id: '5',
    plotId: 'TN-CHN-2023-11098',
    owner: 'Karthik Subramanian',
    location: 'OMR, Chennai, Tamil Nadu',
    price: 9200000,
    area: '1500 sq ft',
    type: 'Commercial',
    status: 'safe',
    registrationDate: '2023-09-05',
    lastTransfer: '2023-09-05',
    ownershipChain: [
      { id: 'oc15', owner: 'CMDA Chennai', role: 'Original Plot', timestamp: '2008-03-22', transferPrice: 1500000, validationStatus: 'verified' },
      { id: 'oc16', owner: 'Lakshmi Properties', role: 'Development', timestamp: '2016-11-08', transferPrice: 5500000, validationStatus: 'verified' },
      { id: 'oc17', owner: 'Karthik Subramanian', role: 'Purchase', timestamp: '2023-09-05', transferPrice: 9200000, validationStatus: 'verified' },
    ],
  },
  {
    id: '6',
    plotId: 'RJ-JAI-2024-00312',
    owner: 'Arun Singh Rathore',
    location: 'Malviya Nagar, Jaipur, Rajasthan',
    price: 6800000,
    area: '2000 sq ft',
    type: 'Residential',
    status: 'review',
    registrationDate: '2024-03-01',
    lastTransfer: '2024-03-01',
    ownershipChain: [
      { id: 'oc18', owner: 'JDA Jaipur', role: 'Land Allotment', timestamp: '2003-07-18', transferPrice: 600000, validationStatus: 'verified' },
      { id: 'oc19', owner: 'Mahendra Builders', role: 'Construction Sale', timestamp: '2014-02-28', transferPrice: 3200000, validationStatus: 'verified' },
      { id: 'oc20', owner: 'Arun Singh Rathore', role: 'Resale Purchase', timestamp: '2024-03-01', transferPrice: 6800000, validationStatus: 'verified' },
    ],
  },
  {
    id: '7',
    plotId: 'GJ-AMD-2024-00455',
    owner: 'Nisha Patel',
    location: 'SG Highway, Ahmedabad, Gujarat',
    price: 12000000,
    area: '1100 sq ft',
    type: 'Commercial',
    status: 'risky',
    registrationDate: '2024-01-22',
    lastTransfer: '2024-01-22',
    ownershipChain: [
      { id: 'oc21', owner: 'AUDA Ahmedabad', role: 'Commercial Allotment', timestamp: '2011-05-10', transferPrice: 2500000, validationStatus: 'verified' },
      { id: 'oc22', owner: 'Sahara Infra Pvt Ltd', role: 'Bulk Purchase', timestamp: '2020-08-15', transferPrice: 7000000, validationStatus: 'verified' },
      { id: 'oc23', owner: 'Phantom Holdings Inc', role: 'Shell Company Transfer', timestamp: '2024-01-10', transferPrice: 10000000, validationStatus: 'suspicious' },
      { id: 'oc24', owner: 'Nisha Patel', role: 'Quick Resale', timestamp: '2024-01-22', transferPrice: 12000000, validationStatus: 'suspicious' },
    ],
  },
  {
    id: '8',
    plotId: 'UP-LKO-2023-07890',
    owner: 'Mohd Iqbal',
    location: 'Gomti Nagar, Lucknow, Uttar Pradesh',
    price: 5500000,
    area: '1600 sq ft',
    type: 'Residential',
    status: 'safe',
    registrationDate: '2023-04-12',
    lastTransfer: '2023-04-12',
    ownershipChain: [
      { id: 'oc25', owner: 'LDA Lucknow', role: 'Allotment', timestamp: '2006-10-25', transferPrice: 900000, validationStatus: 'verified' },
      { id: 'oc26', owner: 'Mohd Iqbal', role: 'Direct Purchase', timestamp: '2023-04-12', transferPrice: 5500000, validationStatus: 'verified' },
    ],
  },
];

export const MOCK_ANALYSIS_RESULTS = {
  '1': { riskLevel: 'low', fraudProbability: 8, disputeProbability: 5, reasons: ['All transfers verified with proper documentation', 'No unusual price escalation patterns', 'Clean ownership chain with adequate holding periods'] },
  '2': { riskLevel: 'high', fraudProbability: 87, disputeProbability: 72, reasons: ['Two rapid transfers within 14 days — classic benami pattern', 'Shell company (Global Realty LLC) involvement detected', '108% price increase in 14-day window', 'Seller entity has 3 other flagged transactions in IGRS database', 'Property under-valued on circle rate by 23%'] },
  '3': { riskLevel: 'low', fraudProbability: 12, disputeProbability: 8, reasons: ['Stable ownership with proper family transfer documentation', 'Market-rate pricing consistent with area average', 'No encumbrance notices found'] },
  '4': { riskLevel: 'medium', fraudProbability: 35, disputeProbability: 28, reasons: ['Recent transfer— documentation verification pending', 'Price 15% above average for Dwarka Sector 12', 'Seller had property for 12 years — normal holding period'] },
  '5': { riskLevel: 'low', fraudProbability: 6, disputeProbability: 3, reasons: ['CMDA approved layout with clear title', 'Commercial property with proper NOC', 'All stamp duties paid and verified'] },
  '6': { riskLevel: 'medium', fraudProbability: 42, disputeProbability: 35, reasons: ['JDA allotment record found but condition compliance pending', 'Builder entity changed name — potential flag', 'Area under smart city project — value reassessment needed'] },
  '7': { riskLevel: 'high', fraudProbability: 91, disputeProbability: 78, reasons: ['Shell company "Phantom Holdings" used as intermediary', 'Two transfers in 12 days', '71% price escalation in under 2 weeks', 'Seller entity registered in tax haven jurisdiction', 'Similar pattern found in 5 other properties on SG Highway'] },
  '8': { riskLevel: 'low', fraudProbability: 4, disputeProbability: 2, reasons: ['Direct purchase from development authority', 'Single ownership transfer — cleanest possible chain', 'All dues and taxes fully cleared'] },
};
